ktor:
    application:
        modules:
            - dev.proflyder.currency.ApplicationKt.module
    deployment:
        port: 8080
        host: 0.0.0.0

bot:
    token: ${BOT_TOKEN:your-bot-token-here}
    chatId: ${CHAT_ID:your-chat-id-here}

scheduler:
    cron: ${SCHEDULER_CRON:0 0 * * * ?}  # Каждый час по умолчанию (секунды минуты часы день месяц день_недели)

database:
    path: ${DATABASE_PATH:data/currency-history}

unkey:
    rootKey: ${UNKEY_ROOT_KEY:your-unkey-root-key-here}